// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitHubNode
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GitHubNodeString = "058f0e26-d2fd-4c6e-8eed-7c6e49e81527";
        public static Guid GitHubNode = new Guid(GitHubNodeString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GitHubRootContextMenu = 0x0001;
        public const int GitHubFolderContextMenu = 0x0002;
        public const int GitHubFileContextMenu = 0x0003;
        public const int AddCopilotSubMenu = 0x0010;
        public const int AddGitHubSubMenu = 0x0011;
        public const int RootAddGroup = 0x0020;
        public const int RootActionsGroup = 0x0021;
        public const int FolderAddGroup = 0x0022;
        public const int FolderActionsGroup = 0x0023;
        public const int FileActionsGroup = 0x0024;
        public const int CopilotSubMenuGroup = 0x0025;
        public const int GitHubSubMenuGroup = 0x0026;
        public const int AddCopilotInstructions = 0x0100;
        public const int AddAgent = 0x0101;
        public const int AddPrompt = 0x0102;
        public const int AddSkill = 0x0103;
        public const int AddWorkflow = 0x0104;
        public const int AddDependabot = 0x0105;
        public const int AddIssueTemplate = 0x0106;
        public const int AddPullRequestTemplate = 0x0107;
        public const int OpenInFileExplorer = 0x0108;
        public const int OpenInFileExplorerFolder = 0x0109;
        public const int OpenContainingFolder = 0x010A;
        public const int CopyPathFolder = 0x010B;
        public const int CopyPathFile = 0x010C;
        public const int RenameFolder = 0x010D;
        public const int RenameFile = 0x010E;
        public const int DeleteFolder = 0x010F;
                public const int DeleteFile = 0x0110;
                public const int AddCodeOwners = 0x0111;
                public const int AddFunding = 0x0112;
                public const int AddSecurity = 0x0113;
            }
        }
